# Generated by Django 4.1.7 on 2023-03-09 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=500, verbose_name='Заказы')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_instagram', models.CharField(max_length=50, verbose_name='Ник в инстаграмме')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('gender', models.CharField(choices=[('MAN', 'Man'), ('WOMAN', 'Woman'), ('BI', 'Bi'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('phone_number', models.IntegerField(verbose_name='Номер телефона ')),
                ('phone_number2', models.IntegerField(verbose_name='Второй номер телефона ')),
                ('payment_receipt', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('delivery_address', models.CharField(max_length=100, verbose_name='Адрес доставки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Заказы', to='order_form.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Размер', to='order_form.size')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
    ]
